//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lockscreen_Swap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lockscreen_Swap.AppResx", typeof(AppResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screen.
        /// </summary>
        public static string AA1 {
            get {
                return ResourceManager.GetString("AA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string AA2 {
            get {
                return ResourceManager.GetString("AA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper.
        /// </summary>
        public static string AA3 {
            get {
                return ResourceManager.GetString("AA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string AA4 {
            get {
                return ResourceManager.GetString("AA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily create a lock screen as in Windows 8.1.
        ///Use your own pictures and see how your lock screen changes every half hour.
        ///There are many options available for this.
        ///You&apos;ll be amazed!.
        /// </summary>
        public static string AAA {
            get {
                return ResourceManager.GetString("AAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.1 Lock Screen.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen changer.
        /// </summary>
        public static string BackgroundTask {
            get {
                return ResourceManager.GetString("BackgroundTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy this app.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy folder.
        /// </summary>
        public static string CopyFolder {
            get {
                return ResourceManager.GetString("CopyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy images to.
        /// </summary>
        public static string CopyImagesTo {
            get {
                return ResourceManager.GetString("CopyImagesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut image.
        /// </summary>
        public static string CutImage {
            get {
                return ResourceManager.GetString("CutImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete images?.
        /// </summary>
        public static string DeleteImages {
            get {
                return ResourceManager.GetString("DeleteImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! Enter name!.
        /// </summary>
        public static string ErrorEnterName {
            get {
                return ResourceManager.GetString("ErrorEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! Name already in use or invalid characters!.
        /// </summary>
        public static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Background agents for this application have been disabled by the user!.
        /// </summary>
        public static string ExError {
            get {
                return ResourceManager.GetString("ExError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (random).
        /// </summary>
        public static string FolderRandom {
            get {
                return ResourceManager.GetString("FolderRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame color.
        /// </summary>
        public static string FrameColor {
            get {
                return ResourceManager.GetString("FrameColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame size.
        /// </summary>
        public static string FrameSize {
            get {
                return ResourceManager.GetString("FrameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info color.
        /// </summary>
        public static string InfoColor {
            get {
                return ResourceManager.GetString("InfoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info transparency.
        /// </summary>
        public static string InfoTransparency {
            get {
                return ResourceManager.GetString("InfoTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string InstGeneralHeader {
            get {
                return ResourceManager.GetString("InstGeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this application to create great background images. This loads of settings are available to you. Your background image is recreated every thirty minutes. It may happen that stops the background service of this application. To start it again, the application must be opened simply..
        /// </summary>
        public static string InstGeneralTXT {
            get {
                return ResourceManager.GetString("InstGeneralTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string InstMiscellaneousHeader {
            get {
                return ResourceManager.GetString("InstMiscellaneousHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate good this application if you like. If you have problems with this application, then please contact support! Questions and issues have lost nothing in the reviews.
        ///Thank you very much!.
        /// </summary>
        public static string InstMiscellaneousTXT {
            get {
                return ResourceManager.GetString("InstMiscellaneousTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string InstPictureHeader {
            get {
                return ResourceManager.GetString("InstPictureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a folder, open it and import, as many images.
        ///When the import of images each image can be aligned.
        ///You can create multiple folders to quickly create a completely different background..
        /// </summary>
        public static string InstPictureTXT {
            get {
                return ResourceManager.GetString("InstPictureTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string InstSettingsHeader {
            get {
                return ResourceManager.GetString("InstSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background can be adjusted on the settings page. Is set the application as a background application, the background image is recreated for each switch. The newly created image is displayed, so that you can immediately check its setting..
        /// </summary>
        public static string InstSettingsTXT {
            get {
                return ResourceManager.GetString("InstSettingsTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string InstSupportHeader {
            get {
                return ResourceManager.GetString("InstSupportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already selected.
        /// </summary>
        public static string IsSet {
            get {
                return ResourceManager.GetString("IsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like xtrose.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You said no, so I can&apos;t update your background..
        /// </summary>
        public static string LockhelperInfo {
            get {
                return ResourceManager.GetString("LockhelperInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string LockscreenFolder {
            get {
                return ResourceManager.GetString("LockscreenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen image (click).
        /// </summary>
        public static string LockscreenImage {
            get {
                return ResourceManager.GetString("LockscreenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set random folder.
        /// </summary>
        public static string LockscreenRandom {
            get {
                return ResourceManager.GetString("LockscreenRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no folders to select. First create an folder and import pictures..
        /// </summary>
        public static string MsgNoFolder {
            get {
                return ResourceManager.GetString("MsgNoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no picture in selected folder. Open folder and import pictures..
        /// </summary>
        public static string MsgNoPicture {
            get {
                return ResourceManager.GetString("MsgNoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other xtrose Apps.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone background.
        /// </summary>
        public static string PhoneBackground {
            get {
                return ResourceManager.GetString("PhoneBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing this app.
        /// </summary>
        public static string PurchaseNote {
            get {
                return ResourceManager.GetString("PurchaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename folder.
        /// </summary>
        public static string RenameFolder {
            get {
                return ResourceManager.GetString("RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select images to copy.
        /// </summary>
        public static string SelectCopy {
            get {
                return ResourceManager.GetString("SelectCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select images to delete.
        /// </summary>
        public static string SelectDelete {
            get {
                return ResourceManager.GetString("SelectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set color.
        /// </summary>
        public static string SetColor {
            get {
                return ResourceManager.GetString("SetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and target are the same.
        /// </summary>
        public static string SourceTarget {
            get {
                return ResourceManager.GetString("SourceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click screen to skip.
        /// </summary>
        public static string StartUpInfo {
            get {
                return ResourceManager.GetString("StartUpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change lock screen.
        /// </summary>
        public static string TaskInfo {
            get {
                return ResourceManager.GetString("TaskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for downloading.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for downloading.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transparent.
        /// </summary>
        public static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Version Expired!.
        /// </summary>
        public static string TrialExpired {
            get {
                return ResourceManager.GetString("TrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Version Expired! To create apps will cost a lot of time. The price for this work is not expensive. To continue create lock screens Images, you must buy the app. Thank you!.
        /// </summary>
        public static string TrialNote {
            get {
                return ResourceManager.GetString("TrialNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial version.
        /// </summary>
        public static string TrialVersion {
            get {
                return ResourceManager.GetString("TrialVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Z01_Add {
            get {
                return ResourceManager.GetString("Z01_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all pictures.
        /// </summary>
        public static string Z01_AllPictures {
            get {
                return ResourceManager.GetString("Z01_AllPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string Z01_Copy {
            get {
                return ResourceManager.GetString("Z01_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cut.
        /// </summary>
        public static string Z01_Cut {
            get {
                return ResourceManager.GetString("Z01_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to automatically.
        /// </summary>
        public static string Z01_CutAuto {
            get {
                return ResourceManager.GetString("Z01_CutAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Z01_Delete {
            get {
                return ResourceManager.GetString("Z01_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading.
        /// </summary>
        public static string Z01_Loading {
            get {
                return ResourceManager.GetString("Z01_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the pictures to the Add.
        /// </summary>
        public static string Z01_MsgSelectImage {
            get {
                return ResourceManager.GetString("Z01_MsgSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiple add.
        /// </summary>
        public static string Z01_MultipleAdd {
            get {
                return ResourceManager.GetString("Z01_MultipleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Z01_Next {
            get {
                return ResourceManager.GetString("Z01_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string Z01_Previous {
            get {
                return ResourceManager.GetString("Z01_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved pictures.
        /// </summary>
        public static string Z01_SavedPictures {
            get {
                return ResourceManager.GetString("Z01_SavedPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string Z01_Select {
            get {
                return ResourceManager.GetString("Z01_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select all.
        /// </summary>
        public static string Z01_SelectAll {
            get {
                return ResourceManager.GetString("Z01_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single add.
        /// </summary>
        public static string Z01_SingleAdd {
            get {
                return ResourceManager.GetString("Z01_SingleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unselect all.
        /// </summary>
        public static string Z01_UnselectAll {
            get {
                return ResourceManager.GetString("Z01_UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply profile.
        /// </summary>
        public static string Z02_ApplyProfile {
            get {
                return ResourceManager.GetString("Z02_ApplyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery info.
        /// </summary>
        public static string Z02_BatteryInfo {
            get {
                return ResourceManager.GetString("Z02_BatteryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy pictures.
        /// </summary>
        public static string Z02_CopyPictures {
            get {
                return ResourceManager.GetString("Z02_CopyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut picture.
        /// </summary>
        public static string Z02_CutPicture {
            get {
                return ResourceManager.GetString("Z02_CutPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut pictures.
        /// </summary>
        public static string Z02_CutPictures {
            get {
                return ResourceManager.GetString("Z02_CutPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Z02_DELETE {
            get {
                return ResourceManager.GetString("Z02_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        public static string Z02_DeleteProfile {
            get {
                return ResourceManager.GetString("Z02_DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Z02_Folders {
            get {
                return ResourceManager.GetString("Z02_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated.
        /// </summary>
        public static string Z02_Generated {
            get {
                return ResourceManager.GetString("Z02_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new.
        /// </summary>
        public static string Z02_GenerateNew {
            get {
                return ResourceManager.GetString("Z02_GenerateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Z02_Images {
            get {
                return ResourceManager.GetString("Z02_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info size.
        /// </summary>
        public static string Z02_InfoSize {
            get {
                return ResourceManager.GetString("Z02_InfoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the app as a lock screen app that we can change your lock screen.
        /// </summary>
        public static string Z02_InfoStart {
            get {
                return ResourceManager.GetString("Z02_InfoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info top.
        /// </summary>
        public static string Z02_InfoTop {
            get {
                return ResourceManager.GetString("Z02_InfoTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My.
        /// </summary>
        public static string Z02_My {
            get {
                return ResourceManager.GetString("Z02_My", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Z02_Profile {
            get {
                return ResourceManager.GetString("Z02_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random folder.
        /// </summary>
        public static string Z02_RandomFolder {
            get {
                return ResourceManager.GetString("Z02_RandomFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random picture.
        /// </summary>
        public static string Z02_RandomPicture {
            get {
                return ResourceManager.GetString("Z02_RandomPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename profile.
        /// </summary>
        public static string Z02_RenameProfile {
            get {
                return ResourceManager.GetString("Z02_RenameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Z02_Save {
            get {
                return ResourceManager.GetString("Z02_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string Z02_SaveSettings {
            get {
                return ResourceManager.GetString("Z02_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select frames.
        /// </summary>
        public static string Z02_SelectFrames {
            get {
                return ResourceManager.GetString("Z02_SelectFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current settings are deleted when the profile is applied.
        /// </summary>
        public static string Z02_WarningSetProfil {
            get {
                return ResourceManager.GetString("Z02_WarningSetProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this application to create great background images. Lots of settings are available to you. Your background image is recreated every thirty minutes.
        ///Windows phone requires an active Internet connection for background services. There is no connection to the Internet the background image can not be re-created.
        ///For the background service is unfortunately only a low memory limit available. It may happen that stops the background service of this application. The application must be opened just to restart it [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Z03_InstGeneralNew {
            get {
                return ResourceManager.GetString("Z03_InstGeneralNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Z03_Language {
            get {
                return ResourceManager.GetString("Z03_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string Z03_Left {
            get {
                return ResourceManager.GetString("Z03_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string Z03_NoteLanguage {
            get {
                return ResourceManager.GetString("Z03_NoteLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application.
        /// </summary>
        public static string Z03_NoteLanguage2 {
            get {
                return ResourceManager.GetString("Z03_NoteLanguage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and share.
        /// </summary>
        public static string Z03_NoteShare {
            get {
                return ResourceManager.GetString("Z03_NoteShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string Z03_Right {
            get {
                return ResourceManager.GetString("Z03_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotate left.
        /// </summary>
        public static string Z03_RotateLeft {
            get {
                return ResourceManager.GetString("Z03_RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotate right.
        /// </summary>
        public static string Z03_RotateRight {
            get {
                return ResourceManager.GetString("Z03_RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Z03_SelectLanguage {
            get {
                return ResourceManager.GetString("Z03_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and share.
        /// </summary>
        public static string Z03_Share {
            get {
                return ResourceManager.GetString("Z03_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Z04_BtnRestore {
            get {
                return ResourceManager.GetString("Z04_BtnRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create.
        /// </summary>
        public static string Z04_ClickToCreate {
            get {
                return ResourceManager.GetString("Z04_ClickToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copmonents.
        /// </summary>
        public static string Z04_Components {
            get {
                return ResourceManager.GetString("Z04_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with xtrose.
        /// </summary>
        public static string Z04_Connecting {
            get {
                return ResourceManager.GetString("Z04_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting......
        /// </summary>
        public static string Z04_ConnectingNow {
            get {
                return ResourceManager.GetString("Z04_ConnectingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string Z04_ConnectionFailed {
            get {
                return ResourceManager.GetString("Z04_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection time out.
        /// </summary>
        public static string Z04_ConnectionTimeOut {
            get {
                return ResourceManager.GetString("Z04_ConnectionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Z04_Contact {
            get {
                return ResourceManager.GetString("Z04_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this frame?
        ///
        ///Deleted context can be restored only through the online installation..
        /// </summary>
        public static string Z04_DeleteFrame {
            get {
                return ResourceManager.GetString("Z04_DeleteFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading......
        /// </summary>
        public static string Z04_Downloading {
            get {
                return ResourceManager.GetString("Z04_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        public static string Z04_Exists {
            get {
                return ResourceManager.GetString("Z04_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended settings.
        /// </summary>
        public static string Z04_Extended {
            get {
                return ResourceManager.GetString("Z04_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        public static string Z04_Frames {
            get {
                return ResourceManager.GetString("Z04_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string Z04_Installed {
            get {
                return ResourceManager.GetString("Z04_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame cannot be deleted.
        ///
        ///This is your last frame. There must be at least one installed..
        /// </summary>
        public static string Z04_LastFrame {
            get {
                return ResourceManager.GetString("Z04_LastFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No components online.
        /// </summary>
        public static string Z04_NoComponentsOnline {
            get {
                return ResourceManager.GetString("Z04_NoComponentsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Z04_Online {
            get {
                return ResourceManager.GetString("Z04_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Z04_Open {
            get {
                return ResourceManager.GetString("Z04_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Z04_RateLater {
            get {
                return ResourceManager.GetString("Z04_RateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Z04_RateNever {
            get {
                return ResourceManager.GetString("Z04_RateNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Z04_RateNow {
            get {
                return ResourceManager.GetString("Z04_RateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application seems to appeal to you.
        ///To program apps is time consuming and difficult.
        ///A good review can help us to spread it further.
        ///
        ///Thank you very much.
        /// </summary>
        public static string Z04_RateText {
            get {
                return ResourceManager.GetString("Z04_RateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select frame to uninstall it. Press here to restore all pre-installed frames..
        /// </summary>
        public static string Z04_Restore {
            get {
                return ResourceManager.GetString("Z04_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore all pre-installed frames.
        /// </summary>
        public static string Z04_RestoreNote {
            get {
                return ResourceManager.GetString("Z04_RestoreNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Z04_Save {
            get {
                return ResourceManager.GetString("Z04_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Z04_Selection {
            get {
                return ResourceManager.GetString("Z04_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show logo on start.
        /// </summary>
        public static string Z04_ShowLogo {
            get {
                return ResourceManager.GetString("Z04_ShowLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Image Tile.
        /// </summary>
        public static string Z04_ShowTile {
            get {
                return ResourceManager.GetString("Z04_ShowTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Z04_Support {
            get {
                return ResourceManager.GetString("Z04_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.0 Lock Screen.
        /// </summary>
        public static string Z05_10_0_LockScreen {
            get {
                return ResourceManager.GetString("Z05_10_0_LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have developed a completely new app!.
        /// </summary>
        public static string Z05_T1 {
            get {
                return ResourceManager.GetString("Z05_T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapted to Windows 10..
        /// </summary>
        public static string Z05_T2 {
            get {
                return ResourceManager.GetString("Z05_T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher resolution. Adapted to the display size..
        /// </summary>
        public static string Z05_T3 {
            get {
                return ResourceManager.GetString("Z05_T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different image formats..
        /// </summary>
        public static string Z05_T4 {
            get {
                return ResourceManager.GetString("Z05_T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background pictures..
        /// </summary>
        public static string Z05_T5 {
            get {
                return ResourceManager.GetString("Z05_T5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field for user informations..
        /// </summary>
        public static string Z05_T6 {
            get {
                return ResourceManager.GetString("Z05_T6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many more opportunities..
        /// </summary>
        public static string Z05_T7 {
            get {
                return ResourceManager.GetString("Z05_T7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new and absolutely brilliant engine creates your new lock screen again and again. And without grid as a template. This make the app easy and brings an infinite variety of combinations..
        /// </summary>
        public static string Z05_T8 {
            get {
                return ResourceManager.GetString("Z05_T8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test now.
        /// </summary>
        public static string Z05_TestNow {
            get {
                return ResourceManager.GetString("Z05_TestNow", resourceCulture);
            }
        }
    }
}
